name: 'Setup Build Environment'
description: 'Setup multi-platform build environment for Better GIMP'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend-electron/package-lock.json
    
    # Linux dependencies
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          pkg-config \
          libopencv-dev \
          libtbb-dev \
          libeigen3-dev \
          ninja-build \
          ccache \
          clang-format \
          clang-tidy
        
        # Install Python build tools
        python -m pip install --upgrade pip
        pip install conan build wheel setuptools
    
    # macOS dependencies
    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install cmake opencv tbb eigen ninja ccache
        python -m pip install --upgrade pip
        pip install conan build wheel setuptools
    
    # Windows dependencies
    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        choco install cmake ninja
        python -m pip install --upgrade pip
        pip install conan build wheel setuptools
    
    # Setup ccache for faster builds
    - name: Setup ccache
      if: runner.os != 'Windows'
      shell: bash
      run: |
        ccache --set-config=max_size=2G
        ccache --set-config=compression=true
        echo "/usr/lib/ccache" >> $GITHUB_PATH
    
    # Configure Conan
    - name: Configure Conan
      shell: bash
      run: |
        conan profile detect --force
        conan profile update settings.compiler.libcxx=libstdc++11 default || true
