name: 'Setup Build Environment'
description: 'Setup cross-platform build environment for Better GIMP'

inputs:
  platform:
    description: 'Target platform (ubuntu-22.04, macos-13, macos-14, windows-2022)'
    required: true
  vcpkg_triplet:
    description: 'vcpkg triplet (x64-linux, x64-osx, arm64-osx, x64-windows)'
    required: true

runs:
  using: 'composite'
  steps:
    # =============================================================================
    # VCPKG SETUP
    # =============================================================================
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
        vcpkgGitCommitId: '2024.07.12'
        vcpkgJsonGlob: '**/vcpkg.json'

    # =============================================================================
    # LINUX SETUP
    # =============================================================================
    
    - name: Install Linux Dependencies
      if: inputs.platform == 'ubuntu-22.04'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          pkg-config \
          libtbb-dev \
          libeigen3-dev \
          libgtk-3-dev \
          libx11-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev \
          libgl1-mesa-dev \
          libasound2-dev

    # =============================================================================
    # MACOS SETUP
    # =============================================================================
    
    - name: Install macOS Dependencies
      if: startsWith(inputs.platform, 'macos')
      shell: bash
      run: |
        brew update
        brew install \
          cmake \
          ninja \
          pkg-config \
          tbb \
          eigen

    - name: Setup Xcode (macOS)
      if: startsWith(inputs.platform, 'macos')
      shell: bash
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        xcrun --show-sdk-path

    # =============================================================================
    # WINDOWS SETUP
    # =============================================================================
    
    - name: Setup MSVC (Windows)
      if: inputs.platform == 'windows-2022'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Windows Dependencies
      if: inputs.platform == 'windows-2022'
      shell: powershell
      run: |
        choco install ninja cmake

    # =============================================================================
    # COMMON SETUP
    # =============================================================================
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.27'

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Cache vcpkg packages
      uses: actions/cache@v3
      with:
        path: |
          ${{ runner.workspace }}/vcpkg/packages
          ${{ runner.workspace }}/vcpkg/installed
        key: vcpkg-${{ inputs.vcpkg_triplet }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ inputs.vcpkg_triplet }}-

    - name: Export Build Environment
      shell: bash
      run: |
        echo "VCPKG_ROOT=${{ runner.workspace }}/vcpkg" >> $GITHUB_ENV
        echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
